name: student-management CI/CD 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout Code 
        uses: actions/checkout@v5
        
