name: student-management CI/CD

on: 
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin 
          java-version: '21'
          cache: maven 

      - name: Build Application
        run: mvn clean package

      - name: Configure Aws Credentials 
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Test AWS Connection
        run: aws sts get-caller-identity

      - name: Upload Artifacts to S3 bucket
        run: aws s3 cp target/*.war s3://mayurcbz.space/student.war

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn sonar:sonar \
            -Dsonar.host.url="$SONAR_HOST_URL" \
            -Dsonar.token="$SONAR_TOKEN"

      - name: SonarQube Quality Gates
        run: |
          STATUS=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=com.school:student-management" \
            | jq -r '.projectStatus.status')
          echo "Quality Gate: $STATUS"
          [ "$STATUS" = "OK" ] || exit 1

      - name: Docker Build Image
        run: | 
          docker build -t studentapp .
          docker images

      - name: Build Successful
        run: echo "student-management Build is successful"
        
